# Generated by Django 4.1 on 2022-08-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=40)),
                ("date", models.DateField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=20, null=True)),
                ("cases", models.IntegerField(blank=True, null=True)),
                (
                    "di_class",
                    models.CharField(
                        blank=True, db_column="class", max_length=12, null=True
                    ),
                ),
            ],
            options={"db_table": "disease", "managed": False,},
        ),
    ]
