# Generated by Django 4.1 on 2022-08-09 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EPaCMonitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="disease", table="disease_copy",),
    ]
