# Generated by Django 4.1 on 2022-08-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EPaCMonitor", "0002_alter_disease_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="disease", table="disease",),
    ]
